### ISSUE TITLE
Rotator Data Issue

### ISSUE THREAD

**Issue by nicholasmello** [Trey2k/RLBotGo#8]
Pitch, Yaw, and Roll show as 0 rather than the actual value. Uncommenting lines panics:
`panic: runtime error: invalid memory address or nil pointer dereference`

https://github.com/Trey2k/RLBotGo/blob/687d586163b22c7f55ca858784ff8d1a8662d1ca/unmarshal.go#L289-L291

**Comment by nicholasmello** [comment]
Outputting the data to console shows it goes through periods of nil and periods of accurate information in a periodic way (Switches back and forth around 3 times a second) but I am not familiar enough with flatbuffers to know what is going wrong

**Comment by Trey2k** [comment]
This was patched in d49aeb7caeb8cdaf7e5a91325dfa4505324df824, it turns out to be known behavior, see commit from rlbot-rust https://github.com/RLBot/rlbot-rust/commit/d328b627bffa80c5fbb6c542f1eef3ba176e105e
